import Head from 'next/head';
import { Provider } from 'react-redux';
import 'bootstrap/dist/css/bootstrap.css'
import Header from '../Components/Sidebar/Header';
import { GlobalStyles, lightTheme, darkTheme } from '../Theme/Theme';
import { ThemeProvider } from "styled-components";
import { useState } from 'react';
import Sidebar from '../Components/Sidebar/Sidebar/Sidebar';
import { store } from '../Redux/Action/Store';


function MyApp({ Component, pageProps }) {
  const [theme, setTheme] = useState("light")

  const toggleTheme = () => {
    theme == 'light' ? setTheme('dark') : setTheme('light');
  }
  console.log(theme);
  return (
    <ThemeProvider theme={theme == 'light' ? lightTheme : darkTheme}>
      <GlobalStyles />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <div className="global">
          <Sidebar />
          <div className="content">
            <Header>
              <button className="btn btn-primary" onClick={toggleTheme}>theme</button>
            </Header>
            <Component {...pageProps} />
          </div>
        </div>
      </Provider>
    </ThemeProvider>

  )
}
export default MyApp
